language: cpp

before_install:
  - sh .travis.prepare
  - sudo apt-get install libnotmuch-dev libboost-all-dev libglibmm-2.4-dev libwebkit-dev libwebkitgtk-3.0 libwebkitgtk-3.0-dev libgtkmm-3.0-dev libgmime-2.6-dev

script: 
  - scons

compiler:
  - clang

notification:
  recipients:
    - eg@gaute.vetsj.com

  email:
    on_success: change
    on_failure: change

